version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile 
    working_dir: /app 
    volumes:
      - ./app:/app 
    ports:
      - "3000:3000" 
    env_file:
      - .env 
    command: yarn dev
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cyberlife
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
